import './globals.css';
import { Inter as FontSans } from 'next/font/google';
import { Metadata } from 'next';
import { RootLayoutProps } from '@/types';
import Header from '@/components/header';

export const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
	fallback: ['sans-serif'],
});

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang='en' suppressHydrationWarning>
			<head />
			<body className={fontSans.variable}>
				<Header />
				<main>{children}</main>
			</body>
		</html>
	);
}
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};
